### ISSUE TITLE
cancell game nest crash

### ISSUE THREAD

**Issue by znichola** [znichola/ft_transcendence#133]
```
nest      | PrismaClientKnownRequestError: 
nest      | Invalid `prisma.game.delete()` invocation in
nest      | /backend/nestjs/src/pong/pong.service.ts:103:33
nest      | 
nest      |   100 
nest      |   101 async cancelGame(gameId: number)
nest      |   102 {
nest      | → 103     await prisma.game.delete(
nest      | An operation failed because it depends on one or more records that were required but not found. Record to delete does not exist.
nest      |     at wn.handleRequestError (/backend/nestjs/node_modules/@prisma/client/runtime/library.js:123:6730)
nest      |     at wn.handleAndLogRequestError (/backend/nestjs/node_modules/@prisma/client/runtime/library.js:123:6119)
nest      |     at wn.request (/backend/nestjs/node_modules/@prisma/client/runtime/library.js:123:5839)
nest      |     at l (/backend/nestjs/node_modules/@prisma/client/runtime/library.js:128:9763)
nest      |     at PongService.cancelGame (/backend/nestjs/src/pong/pong.service.ts:103:9)
```

**Comment by Scelewyn** [comment]
Issue solved by switching to an ID system
