### ISSUE TITLE
Socket issue on tfa login

### ISSUE THREAD

**Issue by Scelewyn** [znichola/ft_transcendence#40]
The following error is logged after doing a tfa login, which completely stops nest

```bash
[Nest] 924  - 10/16/2023, 12:34:05 PM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'emit')
TypeError: Cannot read properties of undefined (reading 'emit')
    at Object.socketOnTimeout [as timeout] (node:_http_server:767:37)
    at TransformOperationExecutor.transform (/backend/nestjs/node_modules/src/TransformOperationExecutor.ts:207:39)   
    at TransformOperationExecutor.transform (/backend/nestjs/node_modules/src/TransformOperationExecutor.ts:327:31)   
    at TransformOperationExecutor.transform (/backend/nestjs/node_modules/src/TransformOperationExecutor.ts:327:31)   
    at TransformOperationExecutor.transform (/backend/nestjs/node_modules/src/TransformOperationExecutor.ts:327:31)   
    at ClassTransformer.instanceToPlain (/backend/nestjs/node_modules/src/ClassTransformer.ts:25:21)
    at Object.classToPlain (/backend/nestjs/node_modules/src/index.ts:23:27)
    at ClassSerializerInterceptor.transformToPlain (/backend/nestjs/node_modules/@nestjs/common/serializer/class-serializer.interceptor.js:56:37)   
    at ClassSerializerInterceptor.serialize (/backend/nestjs/node_modules/@nestjs/common/serializer/class-serializer.interceptor.js:49:20)
```

The error could be because the last part of the login has to be done using Swagger as of now, no issue with a login without 2fa at all.
Will have to check again after implementing the login 2fa code to make sure this does not occur at all (otherwise welcome to 0/100)

**Comment by Scelewyn** [comment]
Issue has been un-issued
